### ISSUE TITLE
Multiple hostnames not supported in namecheap domain provider

### ISSUE THREAD

**Issue by linuxlefty** [jon-walton/ipsync#2]
If the user wishes to set multiple hostnames for a single domain provider, it is not possible

For example, I may update "www.example.com" or "example.com", but not both.

Originally, I tried the config:

```yaml
namecheap:
  test.com:
    hostname: www
    password: password

  test.com:
    hostname: '@'
    password: password
```

But only the last config is kept (i.e. the naked domain will be updated, but not www.example.com)
